GamingStore_Projectoti2/Models/Jogos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GamingStore_Projectoti2.Models
{
    public class Jogos
    {
        public Jogos()
    {
        // inicialização da lista de Vendas de um jogo
        Compras = new HashSet<Detalhes_Compra>();

    }

    [Key]
    public int Id { get; set; }



    [Required]
    [StringLength(30)]
    [Display(Name = "Jogo")]
    public string Nome { get; set; }

    [Required]
    [Display(Name = "Preço")]
    public decimal Preco { get; set; }


    public string Fotografia { get; set; }


    [Required]
    [StringLength(30)]
    public string Plataforma { get; set; }



    // um Jogo pode ser várias vezes comprado
    public virtual ICollection<Detalhes_Compra> Compras { get; set; }


}
}

GamingStore_Projectoti2/Controllers/JogosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GamingStore_Projectoti2.Models;

namespace GamingStore_Projectoti2.Controllers
{
    [Authorize(Roles = "Gestor")] // apenas os gestores têm acesso a esta página
    public class JogosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jogos
        public ActionResult Index(string SearchBy, string search)
        {


            // filtar os jogo pelo seu nome e pela sua plataforma
            if (SearchBy == "Plataforma")


                return View(db.Jogos.Where(x => x.Plataforma == search || search == null).ToList());
            else

                return View(db.Jogos.Where(x => x.Nome.StartsWith(search) || search == null).ToList());

        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Jogos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Jogos jogo = db.Jogos.Find(id);
            if (jogo == null)
            {
                return RedirectToAction("Index");
            }
            Session["Id"] = jogo.Id;
            Session["Metodo"] = "Jogos/Details";

            return View(jogo);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: Jogos/Create
        public ActionResult Create()
        {
            ViewBag.Plataformas = db.Plataformas;
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="jogos"></param>
        /// <param name="uploadFotografia"></param>
        /// <returns></returns>
        // POST: Jogos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Nome,Preco,Plataforma")] Jogos jogo, HttpPostedFileBase uploadFotografia)
        {

            //Escreve a fotografia que foi carregada - O save é efetuado na pasta das imagens do disco rigido
            //Especificar id do jogo
            //testar se há registos na tabela dos jogo

            // vars aux

            string caminho = "";
            bool ficheiroValido = false;




            /// 1º será que foi enviado um ficheiro?
            if (uploadFotografia == null)

            {   // volta ao index porque tem de adicionar foto
                return RedirectToAction("Index");

            }
            else
            {


                /// 2º será que o ficheiro, se foi fornecido, é do tipo correto?

                string mimeType = uploadFotografia.ContentType;
                if (mimeType == "image/jpeg" || mimeType == "image/png")

                {
                    // o ficheiro é do tipo correto

                    /// 3º qual o nome que devo dar ao ficheiro?
                    Guid g;
                    g = Guid.NewGuid(); // obtem os dados para o nome do ficheiro
                    // e qual a extensão do ficheiro?
                    string extensao = Path.GetExtension(uploadFotografia.FileName).ToLower();
                    // montar novo nome
                    string nomeFicheiro = g.ToString() + extensao;
                    // onde guardar o ficheiro?
                    caminho = Path.Combine(Server.MapPath("~/fotografias/"), nomeFicheiro);
                    /// 4º como o associar ao novo Jogo?
                    jogo.Fotografia = nomeFicheiro;

                    // marcar o ficheiro como válido
                    ficheiroValido = true;




                }
                else
                {
                    // o ficheiro fornecido nao é válido 
                    // atributo por defeito ao jogo
                    return RedirectToAction("Index");
                    // jogo.Fotografia = "no-user.jpg";
                }
            }



            // confronta os dados que vem da view com a forma que os dados devem  ter .
            // ie, valida os dados com o modelo
            if (ModelState.IsValid)
            {
                try
                {
                    db.Jogos.Add(jogo);
                    db.SaveChanges();


                    /// 5º como o guardar no disco rígido?
                    if (ficheiroValido)
                    {
                        uploadFotografia.SaveAs(caminho);
                    }
                    return RedirectToAction("Index");

                }
                catch (Exception)
                {


                }
                Session["Id"] = jogo.Id;
                Session["Metodo"] = "Jogos/Create";
                ViewBag.Plataformas = db.Plataformas;

            }

            return View(jogo);



        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Jogos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Jogos jogo = db.Jogos.Find(id);
            if (jogo == null)
            {
                return RedirectToAction("Index");
            }

            Session["Id"] = jogo.Id;
            Session["Metodo"] = "Jogos/Edit";
            ViewBag.Plataformas = db.Plataformas;
            return View(jogo);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="jogos"></param>
        /// <returns></returns>
        // POST: Jogos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Preco,Fotografia,Plataforma")] Jogos jogo, HttpPostedFileBase uploadFotografia)
        {
            string caminho = "";



            if (uploadFotografia == null)
            {

                return RedirectToAction("Index");
            }
            else
            {
                db.Entry(jogo).State = EntityState.Modified;
                string mimeType = uploadFotografia.ContentType;
                if (mimeType == "image/jpeg" || mimeType == "image/png")

                {
                    // o ficheiro é do tipo correto

                    /// 3º qual o nome que devo dar ao ficheiro?
                    Guid g;
                    g = Guid.NewGuid(); // obtem os dados para o nome do ficheiro
                    // e qual a extensão do ficheiro?
                    string extensao = Path.GetExtension(uploadFotografia.FileName).ToLower();
                    // montar novo nome
                    string nomeFicheiro = g.ToString() + extensao;
                    // onde guardar o ficheiro?
                    caminho = Path.Combine(Server.MapPath("~/fotografias/"), nomeFicheiro);
                    /// 4º como o associar ao novo Jogo?
                    jogo.Fotografia = nomeFicheiro;





                }
                else
                {
                    // o ficheiro fornecido nao é válido 
                    // atributo por defeito ao jogo
                    return RedirectToAction("Index");
                    // jogo.Fotografia = "no-user.jpg";
                }
            }


            if (ModelState.IsValid)
            {

                uploadFotografia.SaveAs(caminho);
                db.Entry(jogo).State = EntityState.Modified;

                db.SaveChanges();
                ViewBag.Plataformas = db.Plataformas;
                return View(jogo);

            }
            ViewBag.Plataformas = db.Plataformas;
            return View(jogo);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Jogos/Delete/5
        public ActionResult Delete(int? id)
        {
            // o ID do jogo não foi fornecido
            // não é possível procurar o jogo
            // o que devo fazer?
            if (id == null)
            {
                ///  opção por defeito do 'template'
                ///  return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                /// e não há ID do Jogo, uma de duas coisas aconteceu:
                ///   - há um erro nos links da aplicação
                ///   - Alguem a fazer asneiras no URL

                /// redireciono o utilzador para o ecrã incial
                return RedirectToAction("Index");
            }


            // procura os dados do Jogo, cujo ID é fornecido
           Jogos jogo = db.Jogos.Find(id);

            /// se o jogo não fôr encontrado
            if (jogo == null)
            {
                // ou há um erro,
                // ou há um alguem a tentar mexer no url
                //   return HttpNotFound();

                /// redireciono o utilzador para o ecrã incial
                return RedirectToAction("Index");
            }

            /// para o caso do utilizador alterar, de forma fraudulenta,
            /// os dados do Jogo, vamos guardá-los internamente
            /// Para isso, vou guardar o valor do ID do Jogo
            /// - guardar o ID do Jogo num cookie cifrado
            /// - guardar o ID numa var. de sessão 
           
            Session["IdJogo"] = jogo.Id;
            Session["Metodo"] = "Jogos/Delete";

            // envia para a View os dados do Jogo encontrado

GamingStore_Projectoti2/Views/Jogos/Create.cshtml
@model GamingStore_Projectoti2.Models.Jogos

@{
    ViewBag.Title = "Create";
}

<h2>Adicionar Jogo</h2>
@using (Html.BeginForm("Create",
                        "Jogos",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Jogos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Plataforma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Plataforma, new SelectList(ViewBag.Plataformas, "Nome", "Nome"),
                                                        "Escolha a Plataforma", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Plataforma, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* Adição do objeto para fazer o file upload de uma fotografia sss*@
                @*@Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file" name="uploadFotografia" style="color:blue" accept=".jpg,.png">
                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-success" />
                @Html.ActionLink("Regressar ao Início", "Index", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}
<div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

GamingStore_Projectoti2/Views/Jogos/Delete.cshtml
@model GamingStore_Projectoti2.Models.Jogos

@{
    ViewBag.Title = "Delete";
}

<h2>Apagar</h2>
<h2>Tem a certeza que quer apagar este jogo?</h2>
<div>
    <hr />
   
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>
        <dd>
            <img src="~/fotografias/@Html.DisplayFor(model => model.Fotografia)"
                 alt="imagem do jogo @Html.DisplayFor(model => model.Nome)"
                 title="@Html.DisplayFor(model => model.Nome)"
                 width="150" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Preco)€
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Plataforma)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Plataforma)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-danger" />
            @Html.ActionLink("Regressar ao Início", "Index", null, new { @class = "btn btn-primary" })
        </div>
    }
</div>

GamingStore_Projectoti2/Views/Jogos/Details.cshtml
@model GamingStore_Projectoti2.Models.Jogos

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fotografia)
        </dt>
        <dd>
            <img src="~/fotografias/@Html.DisplayFor(model => model.Fotografia)"
                 alt="imagem do jogo @Html.DisplayFor(model => model.Nome)"
                 title="@Html.DisplayFor(model => model.Nome)"
                 width="150" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Preco)€
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Plataforma)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Plataforma)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" })
    @Html.ActionLink("Regressar ao Início", "Index", null, new { @class = "btn btn-primary" })
</p>

GamingStore_Projectoti2/Views/Jogos/Edit.cshtml
@model GamingStore_Projectoti2.Models.Jogos

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>
@using (Html.BeginForm("Edit",
                        "Jogos",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.Fotografia)
    <img src="~/fotografias/@Html.DisplayFor(model => model.Fotografia)"
         alt="imagem do jogo @Html.DisplayFor(model => model.Nome)"
         title="@Html.DisplayFor(model => model.Nome)"
         width="150" />

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Plataforma, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Plataforma, new SelectList(ViewBag.Plataformas, "Nome", "Nome"),
                                                                        "Escolha a Plataforma", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Plataforma, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @* Adição do objeto para fazer o file upload de uma fotografia sss*@
            @*Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })*@
            <input type="file" name="uploadFotografia" style="color:blue" accept=".jpg" />
            @*Html.TextBoxFor(model => model.Fotografia, new { type = "file", @class = "form-control" })*@
            @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-success" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Regressar ao Início", "Index", null, new { @class = "btn btn-primary" })
</div>

GamingStore_Projectoti2/Views/Jogos/Index.cshtml
@model IEnumerable<GamingStore_Projectoti2.Models.Jogos>

@{
    ViewBag.Title = "Index";
}

<center>
    <h2>Lista de Jogos</h2>
</center>

@using (Html.BeginForm("Index", "Jogos", FormMethod.Get))
{

    <b> Pesquisa por...</b>

    @Html.RadioButton("SearchBy", "Jogo", true) <text>Nome</text>
    @Html.RadioButton("SearchBy", "Plataforma") <text>Plataforma</text>


    <br />
    @Html.TextBox("search")<input type="submit" value="Pesquisa" />
}
     <br><br />
       <p>
       @Html.ActionLink("Adicionar novo jogo", "Create", null, new { @class = "btn btn-primary" })
        </p>
       
@* Displayname-> nome do conteudo *@
@foreach (var item in Model)
{
}<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Plataforma)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fotografia)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Preco)€
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Plataforma)
            </td>
            <td>
                @*Html.DisplayFor(modelItem => item.Fotografia)*@
                <a href="~/fotografias/@item.Fotografia" target="_blank">
                    <img src="~/fotografias/@item.Fotografia" height="50" />
                </a>
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Apagar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
</table>