GamingStore_Projectoti2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GamingStore_Projectoti2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GamingStore_Projectoti2/Controllers/ListaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GamingStore_Projectoti2.Models;

namespace GamingStore_Projectoti2.Controllers
{
  
    public class ListaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// Index que mostra toda a lista dos jogos
        /// </summary>
        /// <param name="SearchBy"></param>
        /// <param name="search"></param>
        /// <returns></returns>
        // GET: Lista
        public ActionResult Index(string SearchBy, string search)
        {
            // filtrar os jogo pelo seu nome e pela sua plataforma
            if (SearchBy == "Plataforma")


                return View(db.Jogos.Where(x => x.Plataforma == search || search == null).ToList());
            else
                return View(db.Jogos.Where(x => x.Nome.StartsWith(search) || search == null).ToList());

        }
          
        
    
        
        /// <summary>
        /// Mostra os detalhes do jogo
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Lista/Details/5

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Jogos jogo = db.Jogos.Find(id);
            if (jogo == null)
            {
                return RedirectToAction("Index");
            }
           
          

            Session["Metodo"] = "";
            return View(jogo);
        }



        /// <summary>
        /// Antes do cliente mandar o jogo para o carrinho, os detalhes do mesmo são mostrados
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Lista/buy/5
       [Authorize(Roles = "Cliente")] // apenas os clientes têm acesso a esta página
        public ActionResult Buy(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Jogos jogo = db.Jogos.Find(id);
            if (jogo == null)
            {
                return RedirectToAction("Index");
            }

           
          
            Session["Metodo"] = "";
           
            return View(jogo);
        }

      



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GamingStore_Projectoti2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GamingStore_Projectoti2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GamingStore_Projectoti2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<header class="masthead mb-auto" style="margin-bottom:10px !important;">

    <style type="text/css">

        body {
            background-image: url('/Fotografias/papel.jpg');
            margin: 0;
        }
    </style>
    <!-- todo o CSS da página principal está aqui -->
    <style .fixedHeightImg>

        img {
            max-height: 400px;
            margin-left: auto;
            margin-right: auto;
            width: auto;
        }

        .btn {
            position: fixed;
            width: 100px;
            height: 100px;
            bottom: 40px;
            right: 40px;
            background-color: #0C9;
            color: #FFF;
            border-radius: 50px;
            text-align: center;
            box-shadow: 2px 2px 3px #999;
        }

        .italic {
            font-style: italic;
            text-shadow: 5px 5px 10px green;
        }
    </style>

    <div class="inner">

        <center>
            <h5 class="italic" style="font-size: 40px">GAMING STORE</h5>
        </center>
        <section id="buttonForm">
            <!-- <table style="float:left" border="1">

                <tr>
                    @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-inline", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <td>

                        <input type="submit" style="width: 100px; height: 50px" class="btn btn-danger" value="Login">
                    </td>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            }
                </tr>
                <tr>
                    @using (Html.BeginForm("Register", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-inline", role = "form" }))
                {
                    @Html.AntiForgeryToken()


                    <td>

                        <input type="submit" style="width: 100px; height: 50px" class="btn btn-primary" value="Registar">
                    </td>
                    @Html.ValidationSummary(true, "", new { @class = "text-primary" })

            }
                </tr>



                <tr>



                    @using (Html.BeginForm("Index", "Lista", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-inline", role = "form" }))
                {
                    @Html.AntiForgeryToken()


                    <td>

                        <input type="submit" style="width: 100px; height: 50px" class="btn btn-success" value="Jogos">
                    </td>
                    @Html.ValidationSummary(true, "", new { @class = "text-sucess" })

            }

                </tr>
            </table>
            -->
        </section>
        @using (Html.BeginForm("Index", "Lista", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-inline", role = "form" }))
        {
            @Html.AntiForgeryToken()



            <div class="item active btn">
                <input align="right" type="submit" class="btn btn-primary" value="Jogos">
                @Html.ValidationSummary(true, "", new { @class = "text-primary" })
            </div>

        }


        <center>
            <div id="myCarousel" max-width="100px" class="carousel slide" data-ride="carousel">
                <!-- Indicadores das  imagens -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                    <li data-target="#myCarousel" data-slide-to="4"></li>
                    <li data-target="#myCarousel" data-slide-to="5"></li>
                </ol>
                <!-- slides -->
                <div class="carousel-inner">
                    <div class="item active fixedHeightImg">
                        <img src="~/Fotografias/ps44.png">
                    </div>
                    <div class="item">
                        <img src="~/Fotografias/PC.jpg">
                    </div>
                    <div class="item">
                        <img src="~/Fotografias/xbox2.jpg">
                    </div>
                    <div class="item">
                        <img src="~/Fotografias/giga.jpg">
                    </div>
                    <div class="item">
                        <img src="~/Fotografias/tap.jpg">
                    </div>
                    <div class="item">
                        <img src="~/Fotografias/coma.jpg">
                    </div>
                </div>
                <!-- controlo para esquerda e direita -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </center>
    </div>
</header>